### ISSUE TITLE
require('os').EOL Character with Webpack fails on Windows

### ISSUE THREAD

**Issue by mtscout6** [demerzel3/karma-sourcemap-loader#12]
I am using this plugin in conjunction with Webpack.

When I run Karma on Mac I get the expected source-mapped exception stack traces. However, no stack traces come through when running on Windows. I'm confident that the existing [`require('os').EOL`](https://github.com/demerzel3/karma-sourcemap-loader/blob/757e612dc4341d1086b69718e5a1f9895f477ca4/index.js#L43) call is the culprit. I added `require('os').EOL = "\n";` as the first line of my `karma.conf.js` file and stack traces with source-maps start working on Windows.

@antialias Is there a particular reason you went with `require('os').EOL` as opposed to "\n"? [`b645a6`](https://github.com/demerzel3/karma-sourcemap-loader/commit/b645a6e148c01a021ba21661f54a5f9552b0a081#diff-168726dbe96b3ce427e7fedce31bb0bcR43)

**Comment by antialias** [comment]
@mtscout6 I went with `require('os').EOL` specifically with cross-platform operability in-mind. I did not test on Windows though, so my attempt was apparently in vain. If https://github.com/demerzel3/karma-sourcemap-loader/pull/13 fixes this on Mac and Windows, then I recommend merging.
