### ISSUE TITLE
Crashes when empty files are in the project.

### ISSUE THREAD

**Issue by tomitrescak** [demerzel3/karma-sourcemap-loader#14]
Hi. In my source map files, I was getting "match" is undefined error on [this line](https://github.com/demerzel3/karma-sourcemap-loader/blob/master/index.js#L49).

```bash
TypeError: Cannot call method 'match' of undefined
    at /usr/local/lib/node_modules/karma-sourcemap-loader/index.js:49:26
    at nextPreprocessor (/usr/local/lib/node_modules/karma/lib/preprocessor.js:59:28)
    at /usr/local/lib/node_modules/karma/lib/preprocessor.js:97:7
    at fs.js:272:14
    at /usr/local/lib/node_modules/karma/node_modules/graceful-fs/graceful-fs.js:104:5
    at Object.oncomplete (fs.js:108:15)

Process finished with exit code 1
```

The problem is, that if there exists by any chance an empty file with "*.js" your plugin will crash karma. A warning or ignore is necesary.

**Comment by rubennorte** [comment]
+1 here. I'll do a PR this evening.

**Comment by rubennorte** [comment]
It wasn't that evening, but not so late. Please, @tomitrescak review and merge the PR and then publish a new version so we can keep using this great plugin.

Thanks!

**Comment by rubennorte** [comment]
Any plans on releasing a new version with this fix?

**Comment by tomitrescak** [comment]
Fix looks good, hopefully soon.

**Comment by demerzel3** [comment]
Sorry for the delay, version 0.3.5 just published with the fix!

**Comment by stevehipwell** [comment]
This is still a problem when there is a typescript interface in a file on its own. There will be an empty .js file with a map file and the pre-processor fails.
