### ISSUE TITLE
sourcemaps don't load with mocha 2.x

### ISSUE THREAD

**Issue by necolas** [demerzel3/karma-sourcemap-loader#15]
I haven't looked into this in any depth, but upgrading from mocha 1.21.5 to 2.2.5 caused sourcemaps to stop working. They are there in the bundle, but not included in console reports when there are test failures.

**Comment by necolas** [comment]
Narrowed it down to a specific version of mocha.

2.2.1 works
2.2.3 doesn't work

**Comment by RomkeVdMeulen** [comment]
Still getting this with `2.2.43`.

**Comment by RomkeVdMeulen** [comment]
Never mind: source mapping works.
