### ISSUE TITLE
Support sourcemaps generated by karma preprocessors

### ISSUE THREAD

**Issue by fatso83** [demerzel3/karma-sourcemap-loader#19]
As reported in babel/karma-babel-preprocessor#19, tests that are transpiled by karma preprocessors do not get their source mapped to the original source in stack traces as this plugin does not take those source maps into account, only the non-test code.

Is this possible to support? I see that karma-source-map-support has support for this, but it has other issues making it less attractive (tschaub/karma-source-map-support#1) ...

**Comment by JaKXz** [comment]
+1 for sure. I'm using the `karma-webpack` preprocessor which loads my TypeScript files into karma, but I'm unfortunately seeing errors like this:

```
      TypeError: Cannot read property 'replace' of undefined
          at Object.makeSelector (/Users/Jason/git/webpack-ts-demo/client/utils/component-maker.spec.ts:9:10062)
          at Context.<anonymous> (/Users/Jason/git/webpack-ts-demo/client/utils/component-maker.spec.ts:9:2070)
```

**Comment by JaKXz** [comment]
@demerzel3 looking at the source code, it shouldn't matter whether the generated sourcemaps are inline or sibling files. Any ideas why this is failing?

**Comment by sshev** [comment]
here's solution for typescript unit tests https://github.com/webpack/karma-webpack/issues/109#issuecomment-224961264

**Comment by guojindai** [comment]
@sshev , this solution also works for jsx. 👍

**Comment by demerzel3** [comment]
very old, closing
