### ISSUE TITLE
Inline sourcemap does not handle charset

### ISSUE THREAD

**Issue by klaascuvelier** [demerzel3/karma-sourcemap-loader#27]
When a charset is specified in  the inline source maps, and it is positioned in front of the base64 indication, the loader does not detect it's base64.

**Comment by demerzel3** [comment]
![Good News](https://cloud.githubusercontent.com/assets/442835/12309764/b96871c4-ba4c-11e5-8d7d-fdb248879f34.png)
Version 0.3.7 is out!
