### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by mwisnicki** [demerzel3/karma-sourcemap-loader#3]
I'm trying to use it with TypeScript and even though I have correct sourcemaps that work with Chrome inspector, karma still prints original stacktraces referring to js files.

**Comment by michikono** [comment]
Since Karma supposedly auto loads all plugins with the pattern `karma-*` ([reference](http://karma-runner.github.io/0.12/config/plugins.html)), I simply omitted the entire plugin block to get around the error.

**Comment by mtscout6** [comment]
I somehow resolved my problem, now it's just a Mac vs Windows problem for me. See #12.
