### ISSUE TITLE
Feature request: ignore transpiled line numbers

### ISSUE THREAD

**Issue by kvcrawford** [demerzel3/karma-sourcemap-loader#30]
It would be nice if there were an option for the console to only print the original source's line number:

![screen shot 2016-05-12 at 11 34 44 am](https://cloud.githubusercontent.com/assets/504158/15226028/e4a1ecc0-1835-11e6-8097-e6491772f48f.png)

In other words, omit `href@/Users/kvcrawford/git/trouter/src/spec/Router.spec.js:19333:71` and only print `webpack:///src/Router.js:59:6`

**Comment by abirmingham** [comment]
@kvcrawford were you able to find a workaround for this? I agree that the output is needlessly verbose.

**Comment by demerzel3** [comment]
very old, closing
