### ISSUE TITLE
https://registry.npmjs.org/karma-sourcemaps-loader is empty

### ISSUE THREAD

**Issue by nicholaspretorius** [demerzel3/karma-sourcemap-loader#37]
Good day, 

Ran npm install from Terminal: npm i -D karma-sourcemaps-loader

Received a 404 error: 

![screen shot 2017-12-19 at 9 07 19 pm](https://user-images.githubusercontent.com/805497/34174141-a27d51ce-e500-11e7-8397-6ddd4bc0b20e.png)

Checked the debug log: 
![screen shot 2017-12-19 at 9 12 18 pm](https://user-images.githubusercontent.com/805497/34174393-5cd680f4-e501-11e7-96c0-bd58761398db.png)

Visited: https://registry.npmjs.org/karma-sourcemaps-loader 

![screen shot 2017-12-19 at 9 04 30 pm](https://user-images.githubusercontent.com/805497/34174046-3f228cac-e500-11e7-909d-3f43af927ee7.png)

**Comment by rally25rs** [comment]
This project name is `karma-sourcemap-loader` not `karma-sourcemaps-loader` (you have an extra "S" in the name).

**Comment by nicholaspretorius** [comment]
Face. Palm. Thank you!
