### ISSUE TITLE
External maps with sourceMappingURL

### ISSUE THREAD

**Issue by nyarly** [demerzel3/karma-sourcemap-loader#4]
traceur generates sourcemaps for file.js at file.map and includes that path in the .js in a sourceMappingURL comment. As far as I can tell, this is correctly spec'd - but sourcemap-loader doesn't find the file.

Could you please add a step to searching for the sourcemap: use non-encoded map path if it's given?

**Comment by demerzel3** [comment]
Should work in the current version, I'm closing the issue. If you are still experiencing the problem please add a comment.

**Comment by kylezeeuwen** [comment]
thanks @jamestalmage that worked for me to clear the 404. Note there is a typo and the key should be 'included' not include:

```
files: [{
    pattern:'**/*.js.map',
    included:false
  },
  ....
]
```

**Comment by jamestalmage** [comment]
@kylezeeuwen Thanks for catching that. I've updated my post.
